#!/bin/bash
# deploy.sh — EMERGENCY local-build deploy. Builds a Docker image from the
# current working tree, SCPs it to a remote host, and runs it via the existing
# docker compose stack using a temporary overlay file. The committed
# docker-compose.yml is never modified; after the overlay is removed the next
# normal `docker compose pull && up -d` reverts to the registry image.
#
# The standard prod flow is to pull the signed multi-arch image from the
# GitHub Actions release pipeline. Use this script ONLY when you need to
# ship uncommitted/local changes for a hotfix or live diagnostic.
#
# Invoked by push-to-prod.sh / push-to-uat.sh after they source the per-target
# env file. Required env: REMOTE_USER REMOTE_HOST SSH_KEY INSTALL_DIR
# Optional: VERSION (defaults to git describe), IMAGE_NAME (defaults to hikyaku),
# DEPLOY_PLATFORM (e.g. linux/arm64 for cross-build).
set -euo pipefail

: "${REMOTE_USER:?REMOTE_USER must be set (source scripts/.env.<target>)}"
: "${REMOTE_HOST:?REMOTE_HOST must be set}"
: "${SSH_KEY:?SSH_KEY must be set}"
: "${INSTALL_DIR:?INSTALL_DIR must be set}"

VERSION="${VERSION:-$(git describe --tags --dirty 2>/dev/null || echo dev)}"
IMAGE_NAME="${IMAGE_NAME:-hikyaku}"
# DEPLOY_PLATFORM lets us cross-build for the remote's architecture (e.g.
# linux/arm64 for a Jetson). Defaults to the local arch — set this in the
# per-target .env file when the remote arch differs.
DEPLOY_PLATFORM="${DEPLOY_PLATFORM:-}"
# Always use docker-compose.yml from INSTALL_DIR on the remote. Don't read
# from the env: COMPOSE_FILE is a Docker-recognised variable that may be set
# in the operator's local shell (direnv, rc files) and would leak across to
# the remote where the absolute path doesn't exist.
REMOTE_COMPOSE_FILE="docker-compose.yml"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

if [ -n "${DEPLOY_PLATFORM}" ]; then
  echo ">> Building ${IMAGE_NAME}:${VERSION} for ${DEPLOY_PLATFORM}"
  docker buildx build --platform "${DEPLOY_PLATFORM}" --load \
    --build-arg VERSION="${VERSION}" -t "${IMAGE_NAME}:${VERSION}" .
else
  echo ">> Building ${IMAGE_NAME}:${VERSION} for local architecture"
  docker build --build-arg VERSION="${VERSION}" -t "${IMAGE_NAME}:${VERSION}" .
fi

echo ">> Saving image to tarball"
docker save "${IMAGE_NAME}:${VERSION}" -o "${TMPDIR}/image.tar"
SIZE=$(du -h "${TMPDIR}/image.tar" | cut -f1)
echo "   Image size: ${SIZE}"

echo ">> SCP to ${REMOTE_USER}@${REMOTE_HOST}"
scp -i "${SSH_KEY}" "${TMPDIR}/image.tar" "${REMOTE_USER}@${REMOTE_HOST}:~/image.tar"

echo ">> Loading image and applying emergency overlay on ${REMOTE_HOST}"
ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "${REMOTE_USER}@${REMOTE_HOST}" \
  bash -s -- "${IMAGE_NAME}" "${VERSION}" "${INSTALL_DIR}" "${REMOTE_COMPOSE_FILE}" <<'EOF'
set -e
IMAGE_NAME="$1"
VERSION="$2"
INSTALL_DIR="$3"
COMPOSE_FILE="$4"

echo "Loading image..."
docker load -i ~/image.tar
rm -f ~/image.tar

# Resolve INSTALL_DIR against the REMOTE $HOME. Tilde paths in .env files
# are a footgun: bash expands them at source-time against the LOCAL $HOME,
# which is meaningless for a different remote user. We require a relative
# path here (or an absolute one), and prepend the remote $HOME ourselves.
case "${INSTALL_DIR}" in
  /*) INSTALL_DIR_EXPANDED="${INSTALL_DIR}" ;;
  *)  INSTALL_DIR_EXPANDED="${HOME}/${INSTALL_DIR}" ;;
esac
cd "${INSTALL_DIR_EXPANDED}"

# Overlay lives in /tmp so we don't need write access to INSTALL_DIR
# (the install dir may be owned by another user — we only need to read
# docker-compose.yml from it).
OVERLAY="$(mktemp -t hikyaku-emergency.XXXXXX.yml)"
trap 'rm -f "${OVERLAY}"' EXIT

cat > "${OVERLAY}" <<COMPOSE
# AUTO-GENERATED by scripts/deploy.sh — safe to delete.
# Pins the hikyaku service to a locally-loaded image instead of pulling
# from the registry, so an emergency build can run alongside the normal
# compose stack without modifying docker-compose.yml.
services:
  hikyaku:
    image: ${IMAGE_NAME}:${VERSION}
    pull_policy: never
COMPOSE

echo "Recreating service with emergency overlay..."
docker compose -f "${COMPOSE_FILE}" -f "${OVERLAY}" up -d --force-recreate

sleep 2
echo "Container status:"
docker ps --filter name="${IMAGE_NAME}" --format "{{.Names}} {{.Status}}  ({{.Image}})"
EOF

echo
echo "Deployed ${IMAGE_NAME}:${VERSION} to ${REMOTE_HOST} (emergency overlay)"
echo "To revert to the registry image:"
echo "  ssh ${REMOTE_USER}@${REMOTE_HOST} 'cd ${INSTALL_DIR} && docker compose pull && docker compose up -d --force-recreate'"
